meta_product_name: "Nico SwimBlog"
meta_title: "SwimBlog - Follow my swims in this app"
meta_description: "Find my most memorable swims here"
meta_image: "eaulibre.png" # should exist in `app/assets/images/`
